// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * One normalized event: an envelope (who, when, what order, which conversation)
 * wrapping a [`payload`](Self::payload) (what happened).
 */
export type AgentEvent = { id: string, sessionId: string, harness: Harness, 
/**
 * Position in the session's event log, and the cursor for reconnecting a UI
 * to a running session. One counter per session, shared by mapped stdout
 * lines and events the app synthesizes itself, seeded from the persisted log
 * on resume. Never sort by `ts` — most Claude Code events omit it.
 */
seq: number, ts: string, turnId: string | null, 
/**
 * `None` = main conversation, `Some` = the subagent that produced this.
 */
subagent: Subagent | null, payload: AgentEventPayload, 
/**
 * `None` on the emitted path — raw lines are archived separately — but
 * always populated for [`AgentEventPayload::Unknown`], which is useless
 * without it.
 */
raw: JsonValue | null, };

/**
 * What happened.
 *
 * Permission request/resolve is deliberately absent: no captured fixture shows
 * their shape, so the variants would be a guess. Add once captured.
 */
export type AgentEventPayload = { "type": "turn_started" } & SessionInfo | { "type": "turn_completed", status: TurnStatus, stopReason: string | null, finalText: string | null, usage: Usage | null, durationMs: number | null, } | { "type": "settings_changed" } & Settings | { "type": "user_message", text: string, images: Array<ImageRef>, } | { "type": "assistant_text", 
/**
 * `Some` only when this content was also streamed, naming the preview
 * it supersedes. `None` — the common case, covering Claude Code
 * subagents and all of Codex — means nothing was streamed and the
 * event simply appends in `seq` order.
 */
block: BlockRef | null, text: string, } | { "type": "reasoning", block: BlockRef | null, text: string, encrypted: boolean, } | { "type": "delta" } & DeltaEvent | { "type": "tool_call_started", callId: string, 
/**
 * The harness's own tool name, verbatim (`"Bash"`, `"apply_patch"`).
 */
name: string, toolType: ToolType, 
/**
 * Always an object. JSON-encoded argument strings are parsed here;
 * unparseable input becomes `{"_unparsed": "…"}` rather than dropped.
 */
input: JsonValue, 
/**
 * Input that isn't JSON at all — Codex's `custom_tool_call.input` is raw
 * JS source.
 */
rawInput: string | null, title: string | null, } | { "type": "tool_call_completed", callId: string, result: ToolResult, } | { "type": "file_edits", callId: string | null, edits: Array<FileEdit>, } | { "type": "subagent_started", agentId: string, label: string, description: string | null, prompt: string | null, } | { "type": "subagent_progress", agentId: string, 
/**
 * What the subagent is doing right now — Claude Code rewrites this per
 * progress event, so it drives a live status line without expanding
 * the subagent's own events.
 */
description: string | null, lastTool: string | null, usage: Usage | null, } | { "type": "subagent_completed", agentId: string, status: string, summary: string | null, usage: Usage | null, } | { "type": "usage_update" } & Usage | { "type": "hook", name: string, event: string, phase: HookPhase, exitCode: number | null, outcome: string | null, } | { "type": "context_compacted", message: string | null, windowNumber: number | null, } | { "type": "error", source: ErrorSource, message: string, fatal: boolean, } | { "type": "unknown", harnessType: string, } | { "type": "unrecognized" };

/**
 * Permission stance for a session, in roughly increasing order of autonomy.
 */
export type ApprovalPolicy = "default" | "acceptEdits" | "plan" | "auto" | "dontAsk" | "bypassPermissions";

/**
 * Joins streamed content to its committed counterpart. A message is often
 * `[text, tool_use, …]` and each block arrives as its own event; Claude Code's
 * committed events carry no index, so the mapper derives one by counting blocks
 * per `message_id` in arrival order.
 */
export type BlockRef = { messageId: string, index: number, };

/**
 * A tool call's identity rides here rather than on [`BlockRef`], which stays a
 * cheap map key. It arrives before any arguments have streamed, so the UI can
 * label the call while [`DeltaEvent::InputDelta`] fragments are still landing.
 */
export type BlockType = { "type": "text" } | { "type": "thinking" } | { "type": "tool_use", id: string, name: string, };

export type ContextWindow = { usedTokens: number, maxTokens: number, };

/**
 * Incremental content for a block.
 *
 * **Deltas are a preview, never the source of truth**: the committed event for
 * the same [`BlockRef`] supersedes whatever they accumulated. Absent deltas are
 * the common case — Codex emits none, Claude Code none for subagent output — so
 * consumers must render correctly without them.
 * Tagged on `delta`, not `type`: [`AgentEventPayload::Delta`] is a newtype
 * variant, so these fields flatten into the payload object alongside its own
 * `type` tag. Two tags of the same name serialize but never deserialize.
 */
export type DeltaEvent = { "delta": "block_start", block: BlockRef, blockType: BlockType, } | { "delta": "text_delta", block: BlockRef, text: string, } | { "delta": "input_delta", block: BlockRef, partialJson: string, } | { "delta": "block_stop", block: BlockRef, };

export type ErrorSource = "harness" | "parser" | "process";

export type FileChange = "add" | "update" | "delete";

export type FileEdit = { path: string, change: FileChange, unifiedDiff: string | null, };

export type Harness = "claude_code" | "codex";

export type HookPhase = "started" | "finished";

export type ImageRef = { path: string | null, url: string | null, mimeType: string | null, };

/**
 * Shared with the harness parsers rather than duplicated — the wire shape
 * matches, so they deserialize straight into this.
 */
export type McpServer = { name: string, 
/**
 * Free-form: `connected`, `pending`, `needs-auth` observed, set undocumented.
 */
status: string, };

export type RateLimit = { usedPercent: number | null, windowMinutes: number | null, 
/**
 * RFC3339, normalized from whatever the harness reports.
 */
resetsAt: string | null, planType: string | null, };

export type SessionIndexItem = { sessionId: string, harness: Harness, 
/**
 * Where the agent actually runs. Equals `project_path` for a normal
 * session; points inside `.claude/worktrees/<name>` for a worktree one.
 */
cwd: string, 
/**
 * Repo root — the grouping key, so worktree sessions still list under
 * their project rather than each becoming a project of their own.
 */
projectPath: string, branch: string | null, 
/**
 * `Some` marks this a worktree session; Claude Code names the branch
 * `worktree-<name>`.
 */
worktreeName: string | null, title: string, 
/**
 * Defaulted so index entries written before this field parse as `Idle`.
 */
status: SessionStatus, created: string, modified: string, archived: boolean, pinned: boolean, };

/**
 * Session-level facts, known at startup.
 */
export type SessionInfo = { cwd: string | null, model: string | null, harnessVersion: string | null, tools: Array<string>, mcpServers: Array<McpServer>, subagentTypes: Array<string>, settings: Settings | null, };

/**
 * What crosses the IPC boundary for one session: its index entry plus the
 * replayed event log. Distinct from [`crate::session::Session`], which owns a
 * child process and cannot be serialized.
 */
export type SessionSnapshot = { events: Array<AgentEvent>, sessionId: string, harness: Harness, 
/**
 * Where the agent actually runs. Equals `project_path` for a normal
 * session; points inside `.claude/worktrees/<name>` for a worktree one.
 */
cwd: string, 
/**
 * Repo root — the grouping key, so worktree sessions still list under
 * their project rather than each becoming a project of their own.
 */
projectPath: string, branch: string | null, 
/**
 * `Some` marks this a worktree session; Claude Code names the branch
 * `worktree-<name>`.
 */
worktreeName: string | null, title: string, 
/**
 * Defaulted so index entries written before this field parse as `Idle`.
 */
status: SessionStatus, created: string, modified: string, archived: boolean, pinned: boolean, };

/**
 * Nothing advances this past `Idle` yet — no turn-completion signal is mapped.
 * It ships now so the on-disk index doesn't need a migration once one is.
 */
export type SessionStatus = "idle" | "in_progress" | "completed";

/**
 * Settings that can change mid-session, so they arrive as events rather than
 * living only on [`SessionInfo`].
 */
export type Settings = { model: string | null, 
/**
 * How much the agent may do without asking. Modeled on Claude Code's
 * `permissionMode`, which is a closed set; Codex's `approval_policy` maps
 * onto these, gaining variants if it turns out to need them.
 */
approvalPolicy: ApprovalPolicy | null, sandbox: string | null, writableRoots: Array<string>, networkAccess: boolean | null, fastMode: string | null, };

/**
 * A running subagent, whose events interleave with the main conversation's on
 * one stdout stream.
 *
 * Claude Code identifies these by `parent_tool_use_id` — the id of the tool
 * call that spawned it, so this equals the `call_id` of the corresponding
 * [`AgentEventPayload::ToolCallStarted`] and is what nests a subagent's work
 * under it. Codex uses `agent_path`.
 */
export type Subagent = { id: string, 
/**
 * Drives the collapsed subagent card's title.
 */
label: string | null, };

export type ToolResult = { 
/**
 * Result content flattened to text; harnesses vary between a bare string
 * and an array of blocks.
 */
text: string, 
/**
 * Harnesses routinely omit the error flag on success, so this defaults to
 * `false` rather than being treated as unknown.
 */
isError: boolean, 
/**
 * The full result payload when the harness supplies a structured one.
 */
structured: JsonValue | null, exitCode: number | null, durationMs: number | null, };

/**
 * A rendering hint — which icon and component to use. Nothing depends on this
 * for correctness, and [`ToolType::Other`] must always render acceptably.
 */
export type ToolType = "shell" | "file_read" | "file_edit" | "search" | "web" | "mcp" | "subagent_spawn" | "other";

/**
 * How a turn ended. Claude Code reports this as `is_error` on its result
 * event; Codex live emits `turn.completed` (a failed turn is uncaptured so
 * far). A user-abort outcome likely deserves its own variant once one has been
 * captured.
 */
export type TurnStatus = "success" | "error";

export type Usage = { inputTokens: number | null, outputTokens: number | null, cachedInputTokens: number | null, cacheWriteTokens: number | null, 
/**
 * Broken out only by harnesses that report it separately; others fold
 * thinking tokens into `output_tokens`.
 */
reasoningTokens: number | null, totalTokens: number | null, costUsd: number | null, contextWindow: ContextWindow | null, rateLimit: RateLimit | null, model: string | null, };
